// GENERATED CODE - DO NOT MODIFY.
//
// Generated by packages/protocol/scripts/gen-dart.mjs from
// packages/protocol/schema/protocol.schema.json.
// Run `node packages/protocol/scripts/gen-dart.mjs` to regenerate.

enum SamplingEffortField {
  start('start'),
  duration('duration'),
  observers('observers'),
  detectionMethods('detectionMethods');

  const SamplingEffortField(this.wireValue);

  final String wireValue;

  static SamplingEffortField fromJson(String value) {
    for (final candidate in values) {
      if (candidate.wireValue == value) {
        return candidate;
      }
    }
    throw FormatException('Unknown SamplingEffortField: $value');
  }

  String toJson() => wireValue;
}

enum CovariateDefinitionType {
  number('number'),
  text('text'),
  boolean('boolean'),
  date('date'),
  enumValue('enum');

  const CovariateDefinitionType(this.wireValue);

  final String wireValue;

  static CovariateDefinitionType fromJson(String value) {
    for (final candidate in values) {
      if (candidate.wireValue == value) {
        return candidate;
      }
    }
    throw FormatException('Unknown CovariateDefinitionType: $value');
  }

  String toJson() => wireValue;
}

String _string(Map<String, dynamic> json, String key) {
  final value = json[key];
  if (value is String) {
    return value;
  }
  throw FormatException('Expected a string at "$key"');
}

int _int(Map<String, dynamic> json, String key) {
  final value = json[key];
  if (value is int) {
    return value;
  }
  throw FormatException('Expected an integer at "$key"');
}

Map<String, dynamic> _object(Map<String, dynamic> json, String key) {
  final value = json[key];
  if (value is Map<String, dynamic>) {
    return value;
  }
  throw FormatException('Expected an object at "$key"');
}

List<String> _stringList(Map<String, dynamic> json, String key) {
  final value = json[key];
  if (value is! List) {
    throw FormatException('Expected a list at "$key"');
  }
  return value.map((item) {
    if (item is String) {
      return item;
    }
    throw FormatException('Expected a string in "$key"');
  }).toList();
}

List<T> _objectList<T>(
  Map<String, dynamic> json,
  String key,
  T Function(Map<String, dynamic>) parse,
) {
  final value = json[key];
  if (value is! List) {
    throw FormatException('Expected a list at "$key"');
  }
  return value.map<T>((item) {
    if (item is Map<String, dynamic>) {
      return parse(item);
    }
    throw FormatException('Expected an object in "$key"');
  }).toList();
}

List<T> _enumList<T>(
  Map<String, dynamic> json,
  String key,
  T Function(String) parse,
) {
  final value = json[key];
  if (value is! List) {
    throw FormatException('Expected a list at "$key"');
  }
  return value.map<T>((item) {
    if (item is String) {
      return parse(item);
    }
    throw FormatException('Expected a string in "$key"');
  }).toList();
}

/// The versioned protocol document shared by app/ and server/ (ADR-0009): taxonomic scope, target list or complete-list mode, allowed detection methods, and required effort and covariate fields.
class ProtocolDocument {
  const ProtocolDocument({
    required this.protocolId,
    required this.version,
    required this.taxonomicScope,
    required this.detectionMethods,
    required this.requiredEffortFields,
    this.targetList,
    this.visitCovariates,
    this.siteCovariates,
  });

  /// Stable identity of the Protocol across its versions.
  final String protocolId;

  /// Monotonic version number of this Protocol version.
  final int version;
  final TaxonomicScope taxonomicScope;

  /// The Detection methods a Visit may choose from.
  final List<DetectionMethod> detectionMethods;

  /// The Sampling effort fields a Visit must record.
  final List<SamplingEffortField> requiredEffortFields;

  /// The taxa a Visit must record a Detection for. Omit it for complete-list mode, where the taxonomic scope defines them.
  final List<TargetTaxon>? targetList;

  /// Covariate definitions a Visit value set must carry.
  final List<CovariateDefinition>? visitCovariates;

  /// Covariate definitions a Site value set must carry.
  final List<CovariateDefinition>? siteCovariates;

  factory ProtocolDocument.fromJson(Map<String, dynamic> json) {
    return ProtocolDocument(
      protocolId: _string(json, 'protocolId'),
      version: _int(json, 'version'),
      taxonomicScope: TaxonomicScope.fromJson(_object(json, 'taxonomicScope')),
      detectionMethods: _objectList<DetectionMethod>(
        json,
        'detectionMethods',
        DetectionMethod.fromJson,
      ),
      requiredEffortFields: _enumList<SamplingEffortField>(
        json,
        'requiredEffortFields',
        SamplingEffortField.fromJson,
      ),
      targetList: json['targetList'] == null
          ? null
          : _objectList<TargetTaxon>(json, 'targetList', TargetTaxon.fromJson),
      visitCovariates: json['visitCovariates'] == null
          ? null
          : _objectList<CovariateDefinition>(
              json,
              'visitCovariates',
              CovariateDefinition.fromJson,
            ),
      siteCovariates: json['siteCovariates'] == null
          ? null
          : _objectList<CovariateDefinition>(
              json,
              'siteCovariates',
              CovariateDefinition.fromJson,
            ),
    );
  }

  Map<String, dynamic> toJson() => {
    'protocolId': protocolId,
    'version': version,
    'taxonomicScope': taxonomicScope.toJson(),
    'detectionMethods': detectionMethods
        .map((value) => value.toJson())
        .toList(),
    'requiredEffortFields': requiredEffortFields
        .map((value) => value.toJson())
        .toList(),
    'targetList': ?targetList?.map((value) => value.toJson()).toList(),
    'visitCovariates': ?visitCovariates
        ?.map((value) => value.toJson())
        .toList(),
    'siteCovariates': ?siteCovariates?.map((value) => value.toJson()).toList(),
  };
}

class TaxonomicScope {
  const TaxonomicScope({required this.taxa});

  /// Taxon identifiers in scope, resolvable against the Project's pinned Taxonomic reference (INV-008).
  final List<String> taxa;

  factory TaxonomicScope.fromJson(Map<String, dynamic> json) {
    return TaxonomicScope(taxa: _stringList(json, 'taxa'));
  }

  Map<String, dynamic> toJson() => {'taxa': taxa};
}

class TargetTaxon {
  const TargetTaxon({required this.taxonRef, this.label});

  final String taxonRef;
  final String? label;

  factory TargetTaxon.fromJson(Map<String, dynamic> json) {
    return TargetTaxon(
      taxonRef: _string(json, 'taxonRef'),
      label: json['label'] == null ? null : _string(json, 'label'),
    );
  }

  Map<String, dynamic> toJson() => {'taxonRef': taxonRef, 'label': ?label};
}

class DetectionMethod {
  const DetectionMethod({required this.id, required this.label});

  final String id;
  final String label;

  factory DetectionMethod.fromJson(Map<String, dynamic> json) {
    return DetectionMethod(
      id: _string(json, 'id'),
      label: _string(json, 'label'),
    );
  }

  Map<String, dynamic> toJson() => {'id': id, 'label': label};
}

class CovariateDefinition {
  const CovariateDefinition({
    required this.name,
    required this.type,
    this.unit,
    this.options,
  });

  final String name;
  final CovariateDefinitionType type;
  final String? unit;
  final List<String>? options;

  factory CovariateDefinition.fromJson(Map<String, dynamic> json) {
    return CovariateDefinition(
      name: _string(json, 'name'),
      type: CovariateDefinitionType.fromJson(_string(json, 'type')),
      unit: json['unit'] == null ? null : _string(json, 'unit'),
      options: json['options'] == null ? null : _stringList(json, 'options'),
    );
  }

  Map<String, dynamic> toJson() => {
    'name': name,
    'type': type.toJson(),
    'unit': ?unit,
    'options': ?options,
  };
}
