-- A Visit is submitted as it stands (ADR-0021): its Survey period, Protocol
-- version and pinned Taxonomic reference columns become nullable, a Detection
-- gains a `provisional_name` and must hold exactly one of a resolved `taxon`
-- or that provisional name (INV-021), and the target-uniqueness index is
-- re-keyed on the effective taxon — `coalesce(taxon, provisional_name)` — so a
-- provisional name counts against a resolved taxon of the same name (INV-003).
--
-- Generated by `drizzle-kit generate` from `src/db/schema.ts`; `IF EXISTS` /
-- `IF NOT EXISTS` guards and the pre-emptive constraint drop keep it
-- replay-safe, like 0013–0015, so the populated-database migration tests can
-- re-apply it to a database that already has it (ARCHITECTURE.md Server-schema
-- compatibility, forward-only).
DROP INDEX IF EXISTS "detection_visit_taxon_target_key";--> statement-breakpoint
ALTER TABLE "detection" ALTER COLUMN "taxon" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "visit" ALTER COLUMN "survey_period_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "visit" ALTER COLUMN "protocol_version_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "visit" ALTER COLUMN "taxonomic_reference_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "visit" ALTER COLUMN "taxonomic_reference_version" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "detection" ADD COLUMN IF NOT EXISTS "provisional_name" text;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "detection_visit_taxon_target_key" ON "detection" USING btree ("visit_id",coalesce("taxon", "provisional_name")) WHERE not "detection"."opportunistic";--> statement-breakpoint
ALTER TABLE "detection" DROP CONSTRAINT IF EXISTS "detection_taxon_exactly_one";--> statement-breakpoint
ALTER TABLE "detection" ADD CONSTRAINT "detection_taxon_exactly_one" CHECK (("detection"."taxon" is null) <> ("detection"."provisional_name" is null));
